[relaychain]
default_command = "./bin/polkadot"
default_args = [ "-lparachain=debug" ]
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  extra_args = [ "-lparachain=debug" ]
  ws_port = 9000
  rpc_port = 9001

  [[relaychain.nodes]]
  name = "bob"
  validator = true
  extra_args = [ "-lparachain=debug" ]
  ws_port = 9010
  rpc_port = 9011

  [[relaychain.nodes]]
  name = "charlie"
  validator = true
  extra_args = [ "-lparachain=debug" ]
  ws_port = 9020
  rpc_port = 9021

  [[relaychain.nodes]]
  name = "dave"
  validator = true
  extra_args = [ "-lparachain=debug" ]
  ws_port = 9030
  rpc_port = 9031

[[parachains]]
id = 100
addToGenesis = true
chain = "westmint-local"
cumulus_based = true

  [[parachains.collators]]
  name = "westmint-collator1"
  command = "./bin/polkadot-parachain"
  args = ["--log=xcm=trace,pallet-assets=trace"]
  ws_port = 9040
  rpc_port = 9041

[[parachains]]
id = 200
addToGenesis = true
cumulus_based = true

  [[parachains.collators]]
  name = "parachain-collator01"
  command = "./bin/polkadot-parachain"
  args = ["--log=xcm=trace,pallet-assets=trace"]
  ws_port = 9050
  rpc_port = 9051

[[hrmp_channels]]
sender = 100
recipient = 200
max_capacity = 8
max_message_size = 512

[[hrmp_channels]]
sender = 200
recipient = 100
max_capacity = 8
max_message_size = 512
